# Generated by Django 4.1.5 on 2023-01-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201129_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shift',
            field=models.TimeField(null=True),
        ),
    ]
